name: Build

on:
  push:
    branches:
      - "**"

env:
  ONSHAPE_API: https://cad.onshape.com
  ONSHAPE_ACCESS_KEY: ${{ secrets.OnshapeAccessKey }}
  ONSHAPE_SECRET_KEY: ${{ secrets.OnshapeSecretKey }}

jobs:
  imports:
    strategy:
      matrix:
        model:
          [
            2wheels_urdf,
            2wheels_mujoco,
            adjustable_height_arm_urdf,
            adjustable_height_arm_mujoco,
            rsk_urdf,
            rsk_mujoco,
            quadruped_urdf,
            quadruped_mujoco,
            dog_urdf,
            dog_mujoco,
            sigmaban2019_urdf,
            sigmaban2019_mujoco,
            orbita_mujoco,
            field_urdf,
            field_mujoco,
          ]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install onshape-to-robot pin mujoco

      - name: Run imports
        run: |
          onshape-to-robot ${{ matrix.model }}

      - name: Checking the model
        run: |
          python check_model.py ${{ matrix.model }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.model }}
          path: ${{ matrix.model }}/robot.*
